pollutant = [
    {
        "id": "TN",
        "code": "w21001",
        "name": "总氮",
        "unit": "mg/L",
        "decimal": 2,
        "sort": 1,
        "Series":{{TNSeries}},
        "Factory":{{TNFactory}},
        "isMain": {{TN启用}},
        "isJiaBiao": {{TN启用}},
        "CYBIndex": 1,
        "isEnable": {{TN启用}}
    },
    {
        "id": "TP",
        "code": "w21011",
        "name": "总磷",
        "unit": "mg/L",       
        "decimal": 2,
        "sort": 2,
        "Series":{{TPSeries}},
        "Factory":{{TPFactory}},
        "isMain": {{TP启用}},
        "isJiaBiao": {{TP启用}},
        "CYBIndex": 2,
        "isEnable": {{TP启用}}
    },
    {
        "id": "COD",
        "code": "w01019",
        "name": "高锰酸盐指数",
        "unit": "mg/L",
        'DevTag':'',
        "decimal": 1,
        "sort": 3,
        "isMain": false,
        "isJiaBiao": false,
        "CYBIndex": 3,
        "isEnable": false
    },
    {
        "id": "NH3",
        "code": "w21003",
        "name": "氨氮",
        "unit": "mg/L",
        "decimal": 2,
        "sort": 4,
        "Series":{{NH3Series}},
        "Factory":{{NH3Factory}},
        "isMain": {{NH3启用}},
        "isJiaBiao": {{NH3启用}},
        "CYBIndex": 4,
        "isEnable": {{NH3启用}}
    }, {
        "id": "CODCR",
        "code": "w01018",
        "name": "化学需氧量",
        "unit": "mg/L",
        "decimal": 1,
        "sort": 5,
        "Series":{{CODCRSeries}},
        "Factory":{{CODCRFactory}},
        "isMain": {{CODCR启用}},
        "isJiaBiao": {{CODCR启用}},
        "CYBIndex": 5,
        "isEnable": {{CODCR启用}}
    },
{
        "id": "WC",
        "code": "WC",
        "name": "五参数",
        "unit": "-",
        "decimal": 2,
        "sort": 6,
        "isMain": false,
        "Series":{{WCSeries}},
        "Factory":{{WCFactory}},
        "isEnable": {{WC启用}}
    },

    {
        "id": "PH",
        "code": "w01001",
        "name": "pH",
        "unit": "-",
        "decimal": 2,
        "sort": 7,
        "isMain": false,
        "Series":{{WCSeries}},
        "Factory":{{WCFactory}},
        "isEnable": {{WC启用}}
    },
    {
        "id": "DianDaoLv",
        "code": "w01014",
        "name": "电导率",
        'DevTag':'',
        "unit": "μS/cm",
        "decimal": 1,
        "sort": 8,
        "isMain": false,
        "isEnable": false
    },
    {
        "id": "HunZhuoDu",
        "code": "w01003",
        "name": "浊度",
        'DevTag':'',
        "unit": "NTU",
        "decimal": 2,
        "sort": 9,
        "isMain": false,
        "isEnable": false
    },
    {
        "id": "RongJieYang",
        "code": "w01009",
        "name": "溶解氧",
        "unit": "mg/L",
        'DevTag':'',
        "decimal": 2,
        "sort": 10,
        "isMain": false,
        "isEnable":false
    },
    {
        "id": "ShuiWen",
        "code": "w01010",
        "name": "水温",
        "unit": "℃",
        "decimal": 1,
        "sort": 11,
        "isMain": false,
        "Series":{{WCSeries}},
        "Factory":{{WCFactory}},
        "isEnable":{{WC启用}}
    },
  {
        "id": "SZY",
        "code": "w22001",
        "name": "水中油",
        "unit": "mg/L",
        "decimal": 2,
        "sort": 15,
        "isMain": false,
        "Series":{{SZYSeries}},
        "Factory":{{SZYFactory}},
        "isEnable": {{SZY启用}}
    },
 {
        "id": "XuanFuWu",
        "code": "w01012",
        "name": "悬浮物",
        "unit": "mg/L",
        "decimal":0,
        "sort": 15,
        "isMain": false,
        "Series":{{XFWSeries}},
        "Factory":{{XFWFactory}},
        "isEnable": {{XFW启用}}
    },
    {
        "id": "ZaoMiDu",
        "code": "w19011",
        "name": "藻密度",
        "unit": "c/mL",
        "decimal": 2,
        "sort": 12,
        "Series":{{ZMDSeries}},
        "Factory":{{ZMDFactory}},
        "isMain": {{ZMD启用}},
        "isEnable": {{ZMD启用}}
    },
    {
        "id": "YeLvSu",
        "code": "w01016",
        "name": "叶绿素",
        "unit": "mg/L",
        "decimal": 2,
        "sort": 13,
        "Series":{{YLSSeries}},
        "Factory":{{YLSFactory}},
        "isMain": {{YLS启用}},
        "isEnable": {{YLS启用}}
    },
 {
        "id": "ZF",
        "code": "ZF",
        "name": "站房",
        "unit": "",
        "decimal": 0,
        "sort": 14,
        "isMain": false,
        "Series":{{ZFSeries}},
        "Factory":{{ZFFactory}},
        "isEnable": {{ZF启用}}
    },

  {
        "id": "DaQiWenDu",
        "code": "w90001",
        "name": "室内温度",
        "unit": "℃",
        "decimal": 2,
        "sort": 15,
        "isMain": false,
        "Series":{{ZFSeries}},
        "Factory":{{ZFFactory}},
        "isEnable": {{ZF启用}}
    },
    {
        "id": "DaQiShiDu",
        "code": "w90002",
        "name": "室内湿度",
        "unit": "%",
        "decimal": 2,
        "sort": 16,
        "isMain": false,
        "Series":{{ZFSeries}},
        "Factory":{{ZFFactory}},
        "isEnable": {{ZF启用}}
    },

    {
        "id": "Flow",
        "code": "w00000",
        "name": "流量",
        "unit": "m³/h",
        "decimal": 2,
        "sort": 17,
        "isMain": false,
        "Series":{{LLJSeries}},
        "Factory":{{LLJFactory}},
        "isEnable": {{LLJ启用}}
    },
       {
        "id": "realFlow",
        "code": "e01203",
        "name": "瞬时流量",
        "unit": "L/s",
        "decimal": 2,
        "sort": 45,
        "isMain": false,
        "Series":{{LLJSeries}},
        "Factory":{{LLJFactory}},
        "isEnable": {{LLJ启用}}
    },
    {
        "id": "CumulativeFlow",
        "code": "e01204",
        "name": "累计流量",
        "unit": "m³",
        "decimal": 2,
        "sort": 46,
        "isMain": false,
        "Series":{{LLJSeries}},
        "Factory":{{LLJFactory}},
        "isEnable": {{LLJ启用}}
    },
    {
        "id": "CYQ",
        "code": "CYQ",
        "name": "采样器",
        "unit": "m³",
        "decimal": 2,
        "sort": 20,
        "isMain": false,
        "Series":{{CYQSeries}},
        "Factory":{{CYQFactory}},
        "isEnable": {{CYQ启用}}
    }
]