pollutant = [
    {
        "id": "TN",
        "code": "w21001",
        "name": "总氮",
        "unit": "mg/L",
        "decimal": 2,
        "sort": 1,
        "Series":{{TNSeries}},
        "Factory":{{TNFactory}},
        "isMain": {{TN启用}},
        "isJiaBiao": {{TNJB启用}},
        "CYBIndex": 1,
        "isEnable": {{TN启用}}
    },
    {
        "id": "TP",
        "code": "w21011",
        "name": "总磷",
        "unit": "mg/L",
        "decimal": 2,
        "sort": 2,
        "Series":{{TPSeries}},
        "Factory":{{TPFactory}},
        "isMain": {{TP启用}},
        "isJiaBiao": {{TPJB启用}},
        "CYBIndex": 2,
        "isEnable": {{TP启用}}
    },
    {
        "id": "COD",
        "code": "w01019",
        "name": "高锰酸盐指数",
        "unit": "mg/L",
        "decimal": 1,
        "sort": 3,
        "Series":{{CODSeries}},
        "Factory":{{CODFactory}},
        "isMain": {{COD启用}},
        "isJiaBiao": {{CODJB启用}},
        "CYBIndex": 3,
        "isEnable": {{COD启用}}
    },
    {
        "id": "NH3",
        "code": "w21003",
        "name": "氨氮",
        "unit": "mg/L",
        "decimal": 2,
        "sort": 4,
        "Series":{{NH3Series}},
        "Factory":{{NH3Factory}},
        "isMain": {{NH3启用}},
        "isJiaBiao": {{NH3JB启用}},
        "CYBIndex": 4,
        "isEnable": {{NH3启用}}
    }, {
        "id": "CODCR",
        "code": "w01018",
        "name": "化学需氧量",
        "unit": "mg/L",
        "decimal": 0,
        "sort": 5,
        "Series":{{CODCRSeries}},
        "Factory":{{CODCRFactory}},
        "isMain": {{CODCR启用}},
        "isJiaBiao": {{CODCRJB启用}},
        "CYBIndex": 5,
        "isEnable": {{CODCR启用}}
    },
{
        "id": "WC",
        "code": "WC",
        "name": "五参数",
        "unit": "-",
        "decimal": 2,
        "sort": 6,
        "Series":{{WCSeries}},
        "Factory":{{WCFactory}},
        "isMain": false,
        "isEnable": {{WC启用}}
    },
    {
        "id": "PH",
        "code": "w01001",
        "name": "pH",
        "unit": "-",
        "decimal": 2,
        "sort": 6,
        "isMain": false,
        "Series":{{WCSeries}},
        "Factory":{{WCFactory}},
        "isEnable": {{WC启用}}
    },
    {
        "id": "DianDaoLv",
        "code": "w01014",
        "name": "电导率",
        "unit": "μS/cm",
        "decimal": 2,
        "sort": 7,
        "isMain": false,
        "Series":{{WCSeries}},
        "Factory":{{WCFactory}},
        "isEnable": {{WC启用}}
    },
    {
        "id": "HunZhuoDu",
        "code": "w01003",
        "name": "浊度",
        "unit": "NTU",
        "decimal": 2,
        "sort": 8,
        "isMain": false,
        "Series":{{WCSeries}},
        "Factory":{{WCFactory}},
        "isEnable": {{WC启用}}
    },
    {
        "id": "RongJieYang",
        "code": "w01009",
        "name": "溶解氧",
        "unit": "mg/L",
        "decimal": 2,
        "sort": 9,
        "isMain": false,
        "Series":{{WCSeries}},
        "Factory":{{WCFactory}},
        "isEnable": {{WC启用}}
    },
    {
        "id": "ShuiWen",
        "code": "w01010",
        "name": "水温",
        "unit": "℃",
        "decimal": 1,
        "sort": 10,
        "isMain": false,
        "Series":{{WCSeries}},
        "Factory":{{WCFactory}},
        "isEnable": {{WC启用}}
    },
    {
        "id": "ZaoMiDu",
        "code": "w19011",
        "name": "藻密度",
        "unit": "c/mL",
        "decimal": 0,
        "sort": 11,
        "isMain": false,
        "Series":{{ZMDSeries}},
        "Factory":{{ZMDFactory}},
        "isEnable": {{ZMD启用}}
    },
    {
        "id": "YeLvSu",
        "code": "w01016",
        "name": "叶绿素",
        "unit": "mg/L",
        "decimal": 0,
        "sort": 12,
        "isMain": false,
        "Series":{{YLSSeries}},
        "Factory":{{YLSFactory}},
        "isEnable": {{YLS启用}}
    },
   {
        "id": "ZF",
        "code": "ZF",
        "name": "站房",
        "unit": "",
        "decimal": 2,
        "sort": 13,
        "isMain": false,
        "Series":{{ZFSeries}},
        "Factory":{{ZFFactory}},
        "isEnable": {{ZF启用}}
    },
  {
        "id": "DaQiWenDu",
        "code": "w90001",
        "name": "室内温度",
        "unit": "℃",
        "decimal": 1,
        "sort": 13,
        "isMain": false,
        "Series":{{ZFSeries}},
        "Factory":{{ZFFactory}},
        "isEnable": {{ZF启用}}
    },
    {
        "id": "DaQiShiDu",
        "code": "w90002",
        "name": "室内湿度",
        "unit": "%",
        "decimal":1,
        "sort": 14,
        "isMain": false,
        "Series":{{ZFSeries}},
        "Factory":{{ZFFactory}},
        "isEnable": {{ZF启用}}
    },
    {
        "id": "SZY",
        "code": "w22001",
        "name": "水中油",
        "unit": "mg/L",
        "decimal": 2,
        "sort": 15,
        "isMain": false,
        "Series":{{SZYSeries}},
        "Factory":{{SZYFactory}},
        "isEnable": {{SZY启用}}
    },
 {
        "id": "SWDX",
        "code": "w01050",
        "name": "生物毒性",
        "unit": "%",
        "decimal": 2,
        "sort": 16,
        "isMain": false,
        "Series":{{SWDXSeries}},
        "Factory":{{SWDXFactory}},
        "isEnable": {{SWDX启用}}
    },
    {
        "id": "CYQ",
        "code": "CYQ",
        "name": "采样器",
        "unit": "m³",
        "decimal": 2,
        "sort": 18,
        "Series":{{LYSeries}},
        "Factory":{{LYFactory}},
        "isMain": {{LY启用}},
        "isEnable": {{LY启用}}
    },
 {
        "id": "ZJS",
        "code": "ZJS",
        "name": "重金属",
        "unit": "mg/L",
        "decimal": 2,
        "sort": 19,
        "isMain": false,
        "Series":{{HMSeries}},
        "Factory":{{HMFactory}},
        "isEnable": {{HM启用}}
    },
    {
        "id": "VOCs",
        "code": "VOCs",
        "name": "VOCs",
        "unit": "μg/L",
        "decimal": 2,
        "sort": 20,
        "isMain": false,
        "Series":{{VOCSSeries}},
        "Factory":{{VOCSFactory}},
        "isEnable": {{VOCS启用}}
    },

   {
        "id": "Qian",
        "code": "w20120",
        "name": "铅",
        "unit": "mg/L",
        "decimal": 5,
        "sort": 21,
        "isMain": false,
        "isEnable": {{w20120启用}}
    },
    {
        "id": "Ge",
        "code": "w20115",
        "name": "镉",
        "unit": "mg/L",
        "decimal": 5,
        "sort": 22,
        "isMain": false,
        "isEnable": {{w20115启用}}
    },
 
    {
        "id": "Tong",
        "code": "w20122",
        "name": "铜",
        "unit": "mg/L",
        "decimal": 5,
        "sort": 23,
        "isMain": false,
        "isEnable": {{w20122启用}}
    },
    {
        "id": "Xin",
        "code": "w20123",
        "name": "锌",
        "unit": "mg/L",
        "decimal": 4,
        "sort": 24,
        "isMain": false,
        "isEnable": {{w20123启用}}
    },
    {
        "id": "ErLvYiWan12",
        "code": "w24017",
        "name": "1,2—二氯乙烷",
        "unit": "μg/L",
        "decimal": 4,
        "sort": 25,
        "isMain": false,
        "isEnable": {{w24017启用}}
    },
    {
        "id": "JiaBen",
        "code": "w25003",
        "name": "甲苯",
        "unit": "μg/L",
        "decimal": 3,
        "sort": 26,
        "isMain": false,
        "isEnable": {{w25003启用}}
    },
    {
        "id": "LvBen",
        "code": "w25010",
        "name": "氯苯",
        "unit": "μg/L",
        "decimal": 2,
        "sort": 27,
        "isMain": false,
        "isEnable": {{w25010启用}}
    },
    {
        "id": "ErLvBen12",
        "code": "w25011",
        "name": "1,2-二氯苯",
        "unit": "μg/L",
        "decimal": 3,
        "sort": 28,
        "isMain": false,
        "isEnable": {{w25011启用}}
    },
    {
        "id": "ErLvBen14",
        "code": "w25013",
        "name": "1,4-二氯苯",
        "unit": "μg/L",
        "decimal": 3,
        "sort": 29,
        "isMain": false,
        "isEnable": {{w25013启用}}
    },
    {
        "id": "YiBingBen",
        "code": "w25034",
        "name": "异丙苯",
        "unit": "μg/L",
        "decimal": 4,
        "sort": 30,
        "isMain": false,
        "isEnable": {{w25034启用}}
    },
    {
        "id": "BenYiXi",
        "code": "w25038",
        "name": "苯乙烯",
        "unit": "μg/L",
        "decimal": 2,
        "sort": 31,
        "isMain": false,
        "isEnable": {{w25038启用}}
    },
    {
        "id": "DuiWenErJiaBen",
        "code": "w25073",
        "name": "对,间二甲苯",
        "unit": "μg/L",
        "decimal": 3,
        "sort": 32,
        "isMain": false,
        "isEnable": {{w25073启用}}
    },
    {
        "id": "SanXiuJiaWan",
        "code": "w24009",
        "name": "三溴甲烷",
        "unit": "μg/L",
        "decimal": 3,
        "sort": 33,
        "isMain": false,
        "isEnable": {{w24009启用}}
    },
    {
        "id": "SanLvJiaWan",
        "code": "w24004",
        "name": "三氯甲烷",
        "unit": "μg/L",
        "decimal": 4,
        "sort": 34,
        "isMain": false,
        "isEnable": {{w24004启用}}
    },
    {
        "id": "LinErJiaBen",
        "code": "w25006",
        "name": "邻二甲苯",
        "unit": "μg/L",
        "decimal": 3,
        "sort": 35,
        "isMain": false,
        "isEnable": {{w25006启用}}
    },
    {
        "id": "YiErLvYiXi11",
        "code": "w24047",
        "name": "1,1-二氯乙烯",
        "unit": "μg/L",
        "decimal": 6,
        "sort": 36,
        "isMain": false,
        "isEnable": {{w24047启用}}
    },
    {
        "id": "YiErLvYiXi12",
        "code": "w24048",
        "name": "1,2-二氯乙烯",
        "unit": "μg/L",
        "decimal": 6,
        "sort": 37,
        "isMain": false,
        "isEnable": {{w24048启用}}
    },
    {
        "id": "YiBen",
        "code": "w25004",
        "name": "乙苯",
        "unit": "μg/L",
        "decimal": 3,
        "sort": 38,
        "isMain": false,
        "isEnable": {{w25004启用}}
    },
    {
        "id": "ErLvJiaWan",
        "code": "w24003",
        "name": "二氯甲烷",
        "unit": "μg/L",
        "decimal": 4,
        "sort": 39,
        "isMain": false,
        "isEnable": {{w24003启用}}
    },
    {
        "id": "SanLvYiXi",
        "code": "w24049",
        "name": "三氯乙烯",
        "unit": "μg/L",
        "decimal": 4,
        "sort": 40,
        "isMain": false,
        "isEnable": {{w24049启用}}
    },
    {
        "id": "SiLvYiXi",
        "code": "w24050",
        "name": "四氯乙烯",
        "unit": "μg/L",
        "decimal": 4,
        "sort": 41,
        "isMain": false,
        "isEnable": {{w24050启用}}
    },
    {
        "id": "Ben",
        "code": "w25002",
        "name": "苯",
        "unit": "μg/L",
        "decimal": 5,
        "sort": 42,
        "isMain": false,
        "isEnable": {{w25002启用}}
    },
  {
        "id": "Flow",
        "code": "w00000",
        "name": "流量",
        "unit": "m³/h",
        "decimal": 2,
        "sort": 43,
        "isMain": false,
        "Series":{{LLJSeries}},
        "Factory":{{LLJFactory}},
        "isEnable": {{LLJ启用}}
    },
   {
        "id": "WaterLevelFlow",
        "code": "e01201",
        "name": "水位",
        "unit": "m³",
        "decimal": 2,
        "sort": 44,
        "isMain": false,
        "Series":{{LLJSeries}},
        "Factory":{{LLJFactory}},
        "isEnable": {{LLJ启用}}
    },
    {
        "id": "realFlow",
        "code": "e01203",
        "name": "瞬时流量",
        "unit": "L/s",
        "decimal": 2,
        "sort": 45,
        "isMain": false,
        "Series":{{LLJSeries}},
        "Factory":{{LLJFactory}},
        "isEnable": {{LLJ启用}}
    },
    {
        "id": "CumulativeFlow",
        "code": "e01204",
        "name": "累计流量",
        "unit": "m³",
        "decimal": 2,
        "sort": 46,
        "isMain": false,
        "Series":{{LLJSeries}},
        "Factory":{{LLJFactory}},
        "isEnable": {{LLJ启用}}
    },

    {
        "id": "BenAn",
        "code": "w26001",
        "name": "苯胺",
        "unit": "mg/L",
        "decimal": 3,
        "sort": 47,
        "isMain": false,
        "Series":{{ANSeries}},
        "Factory":{{ANFactory}},
        "isEnable": {{AN启用}}
    },
   {
        "id": "YeWeiJi",
        "code": "e01201",
        "name": "液位计",
        "unit": "m",
        "decimal": 2,
        "sort": 48,
        "isMain": false,
        "Series":{{YWJSeries}},
        "Factory":{{YWJFactory}},
        "isEnable": {{YWJ启用}}
    },
 {
        "id": "GPSLongitude",
        "code": "e01101",
        "name": "经度",
        "unit": "°",
        "decimal": 2,
        "sort": 49,
        "isMain": false,
        "Series":{{GPSSeries}},
        "Factory":{{GPSFactory}},
        "isEnable": {{GPS启用}}
    },
 {
        "id": "GPSLatitude",
        "code": "e01102",
        "name": "纬度",
        "unit": "°",
        "decimal": 2,
        "sort": 50,
        "isMain": false,
        "Series":{{GPSSeries}},
        "Factory":{{GPSFactory}},
        "isEnable": {{GPS启用}}
    },
   {
        "id": "QX",
        "code": "QX",
        "name": "气象",
        "unit": "-",
        "decimal": 2,
        "sort": 51,
        "isMain": false,
        "Series":{{QXSeries}},
        "Factory":{{QXFactory}},
        "isEnable": {{QX启用}}
    },
 {
        "id": "QXWenDu",
        "code": "e01001",
        "name": "大气温度",
        "unit": "℃",
        "decimal": 2,
        "sort": 51,
        "isMain": false,
        "Series":{{QXSeries}},
        "Factory":{{QXFactory}},
        "isEnable": {{QX启用}}
    },
 {
        "id": "QXShiDu",
        "code": "e01002",
        "name": "大气湿度",
        "unit": "%",
        "decimal": 2,
        "sort": 52,
        "isMain": false,
        "Series":{{QXSeries}},
        "Factory":{{QXFactory}},
        "isEnable": {{QX启用}}
    },
 {
        "id": "QXWindSpeed",
        "code": "e01301",
        "name": "风速",
        "unit": "m/s",
        "decimal": 2,
        "sort": 53,
        "isMain": false,
        "Series":{{QXSeries}},
        "Factory":{{QXFactory}},
        "isEnable": {{QX启用}}
    },
 {
        "id": "QXWindDirection",
        "code": "e01302",
        "name": "风向",
        "unit": "°",
        "decimal": 2,
        "sort": 54,
        "isMain": false,
        "Series":{{QXSeries}},
        "Factory":{{QXFactory}},
        "isEnable": {{QX启用}}
    },
 {
        "id": "QXYaLi",
        "code": "e01901",
        "name": "压力",
        "unit": "kpa",
        "decimal": 2,
        "sort": 55,
        "isMain": false,
        "Series":{{QXSeries}},
        "Factory":{{QXFactory}},
        "isEnable": {{QX启用}}
    },
 {
        "id": "QXMinRainfall",
        "code": "e01303",
        "name": "分钟降雨量",
        "unit": "mm",
        "decimal": 2,
        "sort": 56,
        "isMain": false,
        "Series":{{QXSeries}},
        "Factory":{{QXFactory}},
        "isEnable": {{QX启用}}
    },
 {
        "id": "QXHourRainfall",
        "code": "e013031",
        "name": "小时降雨量",
        "unit": "mm",
        "decimal": 2,
        "sort": 57,
        "isMain": false,
        "Series":{{QXSeries}},
        "Factory":{{QXFactory}},
        "isEnable": {{QX启用}}
    },
 {
        "id": "QX24HourRainfall",
        "code": "e013032",
        "name": "24小时降雨量",
        "unit": "mm",
        "decimal": 2,
        "sort": 58,
        "isMain": false,
        "Series":{{QXSeries}},
        "Factory":{{QXFactory}},
        "isEnable": {{QX启用}}
    },
 {
        "id": "QXLeiJiRainfall",
        "code": "e013033",
        "name": "累计降雨量",
        "unit": "mm",
        "decimal": 2,
        "sort": 59,
        "isMain": false,
        "Series":{{QXSeries}},
        "Factory":{{QXFactory}},
        "isEnable": {{QX启用}}
    },
 {
        "id": "BMS_surplus1",
        "code": "e010041",
        "name": "电池1",
        "unit": "%",
        "decimal": 2,
        "sort": 60,
        "isMain": false,
        "Series":{{BMSSeries}},
        "Factory":{{BMSFactory}},
        "isEnable": {{BMS启用}}
    },
 {
        "id": "BMS_surplus2",
        "code": "e010042",
        "name": "电池2",
        "unit": "%",
        "decimal": 2,
        "sort": 61,
        "isMain": false,
        "Series":{{BMSSeries}},
        "Factory":{{BMSFactory}},
        "isEnable": {{BMS启用}}
    },
 {
        "id": "BMS_surplus3",
        "code": "e010043",
        "name": "电池3",
        "unit": "%",
        "decimal": 2,
        "sort": 62,
        "isMain": false,
        "Series":{{BMSSeries}},
        "Factory":{{BMSFactory}},
        "isEnable": {{BMS启用}}
    },
 {
        "id": "BMS_surplus4",
        "code": "e010044",
        "name": "电池4",
        "unit": "%",
        "decimal": 2,
        "sort": 63,
        "isMain": false,
        "Series":{{BMSSeries}},
        "Factory":{{BMSFactory}},
        "isEnable": {{BMS启用}}
    },
 {
        "id": "BMS_surplus5",
        "code": "e010045",
        "name": "电池5",
        "unit": "%",
        "decimal": 2,
        "sort": 64,
        "isMain": false,
        "Series":{{BMSSeries}},
        "Factory":{{BMSFactory}},
        "isEnable": {{BMS启用}}
    },
 {
        "id": "ZFL",
        "code": "e01902",
        "name": "蒸发量",
        "unit": "mm",
        "decimal": 2,
        "sort": 65,
        "isMain": false,
        "Series":{{ZFYSeries}},
        "Factory":{{ZFYFactory}},
        "isEnable": {{ZFY启用}}
    },
]